# Generated by Django 5.0.6 on 2024-05-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id_anuncio', models.AutoField(db_column='ID_Anuncio', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='Titulo', max_length=255)),
                ('autor', models.CharField(db_column='Autor', max_length=255)),
                ('editora', models.CharField(db_column='Editora', max_length=255)),
                ('edicao', models.IntegerField(db_column='Edicao')),
                ('genero', models.CharField(db_column='Genero', max_length=255)),
                ('idioma', models.CharField(db_column='Idioma', max_length=255)),
                ('valor', models.DecimalField(db_column='Valor', decimal_places=2, max_digits=10)),
                ('cidade', models.CharField(db_column='Cidade', max_length=255)),
                ('cep_anuncio', models.CharField(db_column='CEP_Anuncio', max_length=8)),
                ('latitude', models.DecimalField(db_column='Latitude', decimal_places=5, max_digits=10)),
                ('longitude', models.DecimalField(db_column='Longitude', decimal_places=5, max_digits=10)),
                ('descricao', models.CharField(db_column='Descricao', max_length=1024)),
                ('ano_impressao', models.IntegerField(db_column='Ano_Impressao')),
                ('condicao', models.CharField(db_column='Condicao', max_length=255)),
            ],
            options={
                'db_table': 'anuncio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id_avaliacao', models.AutoField(db_column='ID_Avaliacao', primary_key=True, serialize=False)),
                ('estrelas_produto', models.IntegerField(db_column='Estrelas_Produto')),
                ('estrelas_vendedor', models.IntegerField(db_column='Estrelas_Vendedor')),
                ('comentario', models.TextField(blank=True, db_column='Comentario', null=True)),
            ],
            options={
                'db_table': 'avaliacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(db_column='ID_Comentario', primary_key=True, serialize=False)),
                ('autor', models.CharField(db_column='Autor', max_length=11)),
                ('texto', models.CharField(db_column='Texto', max_length=1024)),
            ],
            options={
                'db_table': 'comentario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id_transacao', models.AutoField(db_column='ID_Transacao', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'transacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cpf_usuario', models.CharField(db_column='CPF_Usuario', max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('data_nascimento', models.DateField(db_column='Data_nascimento')),
                ('telefone', models.CharField(db_column='Telefone', max_length=13)),
                ('email', models.CharField(db_column='Email', max_length=255)),
                ('cep', models.CharField(db_column='CEP', max_length=8)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
