# Generated by Django 5.0.6 on 2024-07-22 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbookbazar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
    ]
