# Generated by Django 5.0.4 on 2024-07-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbookbazar', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('username', models.CharField(max_length=155, primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'credentials',
                'managed': False,
            },
        ),
    ]
