name: Django CI

on:
  push:
    branches: [ "backend" ]
  pull_request:
    branches: [ "backend" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev libssl-dev libffi-dev

    - name: Upgrade pip and setuptools
      run: |
        python -m pip install --upgrade pip setuptools wheel    
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/bookbazar/requirements.txt
    - name: Run Tests
      run: |
        python backend/bookbazar/manage.py test
